### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AZ500-AzureSecurityTechnologies.zh-tw#1]
English: 
How should I use these files relative to the released MOC files?

Current Translation:
我該如何使用與相對於已釋放的 MOC 檔案之這些檔案

Suggested Translation:
相對於發佈的 MOC 檔案，我應該如何使用這些檔案？

Description:
Mistranslation

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
Run bugfix tool and waiting for result.

**Comment by stonezy123** [comment]
![image](https://user-images.githubusercontent.com/49666210/184303989-1505ae56-dc27-4670-b53d-58ca7c0a1d1f.png)
