### ISSUE TITLE
LAB_13_Azure Monitor.md

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AZ500-AzureSecurityTechnologies.zh-tw#31]
English: 
User

Current Translation:
User

Suggested Translation:
使用者

Description:
According to the context, it should be translated. Global check

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
Run bugfix tool and waiting for result.

**Comment by stonezy123** [comment]
![image](https://user-images.githubusercontent.com/49666210/184091208-0088ecf0-8bce-4e32-b746-10c7ccc854c7.png)
